title: Team Hydra Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://eloquent-spence-b692ba.netlify.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Cluster 0
      category: Zira
      description: Spicy-1
    - name: Cluster 1
      category: Zira
      description: Spicy-1
    - name: Cluster 2
      category: Zira
      description: Spicy-1
    - name: Cluster 3
      category: Zira
      description: Spicy-1
    - name: Cluster 4
      category: Zira
      description: Spicy-2
    - name: Cluster 5
      category: Zira
      description: Spicy-2
    - name: Cluster 6
      category: Zira
      description: Spicy-2
    - name: Cluster 7
      category: Zira
      description: Spicy-1
    - name: Cluster 8
      category: Zira
      description: Spicy-3
    - name: Cluster 9
      category: Zira
      description: Spicy-3
    - name: Cluster 10
      category: Zira
      description: Spicy-3
    - name: Cluster 11
      category: Zira
      description: Spicy-3
    - name: Cluster 12
      category: Zira
      description: George-1
    - name: Cluster 13
      category: Zira
      description: George-1
    - name: Cluster 14
      category: Zira
      description: George-2
    - name: Cluster 15
      category: Zira
      description: George-2
    - name: Cluster 16
      category: Zira
      description: George-3
    - name: Cluster 17
      category: Zira
      description: George-3
    - name: Cluster 18
      category: Zira
      description: George-4
    - name: Cluster 19
      category: Zira
      description: George-4
    - name: HepBoat
      category: Team Hydra Bots
      description: The public instance of HepBoat
    - name: HepBoat Prime
      category: Team Hydra Bots
      description: The premium instance of HepBoat for very large servers
    - name: HepBoat Beta
      category: Team Hydra Bots
      description: The beta instance of HepBoat
    - name: Zira Musics
      category: Team Hydra Bots
      description: All instances of Zira Music
    - name: FeedBot
      category: Team Hydra Bots
      description: RSS monitoring and posting bot
    - name: Hydra Modmail
      category: Team Hydra Bots
      description: All modmail bots provided by Team Hydra, including the manager
    - name: AppBot
      category: Team Hydra Bots
      description: Application bot system status
    - name: KeyBot
      category: Team Hydra Bots
      description: Steam and Discord key distribution bot.
    - name: Hep.gg
      category: Team Hydra Services
      description: ShareX Image Host.
    - name: Team Hydra Forums
      category: Team Hydra Services
      description: The forums for Team Hydra.
    - name: TopCord
      category: Team Hydra Services
      description: A bot list powered by Team Hydra.
    - name: Slipstream
      category: Team Hydra Partners
      descripton: A Warframe bot powered by Team Hydra.
    - name: Brilliance Bot
      category: Team Hydra Partners
      description: A bot for the House of Brilliance powered by Team Hydra.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: https://hep.gg/hydralogo
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Zira
      description: Cluster status is listed here
      closed: true
    - name: Team Hydra Bots
      description: All other Team Hydra's other bots.
      closed: false
    - name: Team Hydra Services
      description: All of Team Hydra's services.
      closed: false
    - name: Team Hydra Partners
      description: Partner services of Team Hydra will be listed here.
      closed: true
  description: TESTING status page of Team Hydra services.
  enableCustomHTML: false
  useLargeHeaderDesign: true
